### PR TITLE
Fix broken options parsing

### PR DESCRIPTION
**Pull request by imobach**
semicolon-as-param-name
This patch should fix [bsc#954494](https://bugzilla.suse.com/show_bug.cgi?id=954494). The problem is that if you use yast2-slp-server 2.17.6, due to bug [bsc#878892](https://bugzilla.suse.com/show_bug.cgi?id=878892), you'll get options like this:

```
; net.slp.DAHeartBeat 
```
including an extra space at the end, instead of:
```
;net.slp.DAHeartBeat = 10800
```
which was the original value.

After updating to 2.17.7, the semicolon will be considered the param name of the option (screenshot attached).

I've tested this patch on SLE11 SP3 but I'd like someone more to try it.

### CODE REVIEW

**Comment by mvidner** [comment]
Huh, it looks tricky. And we have no tests for the parsing :-/

**Comment by imobach** [comment]
Yes, I agree. I've done some manual tests and for that reason I wanted more people to try it (or propose another approach). Thanks!

**Comment by mvidner** [comment]
I think a workable approach is to make a testsuite for the parser in master, where we have the infrastructure for SCR chrooting. Once we have tests and understand the fix, we just port it to SLE11.

**Comment by imobach** [comment]
@mvidner It sounds like a good plan. I'll start working on it. Thanks!

**Comment by imobach** [comment]
As this patch could be dangerous, we're implementing tests on `SLE-12-GA branch` to make sure this expression works. See https://github.com/yast/yast-slp-server/pull/13.

**Comment by jreidinger** [comment]
@mvidner now it is merged in master, so can this be proceed?

**Comment by mvidner** [comment]
The tests for this maintenance fix are in the SLE 12 codebase in #13.
LGTM!

**Comment by imobach** [comment]
@mvidner Thanks. Merging...

**Pull request merged**
